# Generated by Django 5.2 on 2025-06-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_herobackgroundimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Applications'), ('mobile', 'Mobile Applications'), ('api', 'APIs & Backend Services'), ('os', 'OS & Low-Level Programming')], max_length=20)),
                ('launch_date', models.DateField()),
                ('project_url', models.URLField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='firstapp.project')),
            ],
        ),
    ]
