# Generated by Django 5.2 on 2025-06-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_section',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='firstapp.project'),
        ),
    ]
