# Generated by Django 5.2 on 2025-06-30 18:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_review_section_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='no description', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
