# Generated by Django 5.2 on 2025-06-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_rename_description_project_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Application', 'Web Applications'), ('Mobile Application', 'Mobile Applications'), ('API & Backend Service', 'APIs & Backend Services'), ('OS & Low-Level Programming', 'OS & Low-Level Programming')], max_length=50),
        ),
    ]
